export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const REMOVE_PRODUCT_SUCCESS = 'REMOVE_PRODUCT_SUCCESS';

export const ADD_USER_INFO_SUCCESS = 'ADD_USER_INFO_SUCCESS';
export const CREATE_NEW_USER_INFO_SUCCESS = 'CREATE_NEW_USER_INFO_SUCCESS';
export const UPDATE_USER_INFO_SUCCESS = 'UPDATE_USER_INFO_SUCCESS';
export const REMOVE_USER_INFO_SUCCESS = 'REMOVE_USER_INFO_SUCCESS';

export const ADD_TICKET_SUCCESS = 'ADD_TICKET_SUCCESS';
export const CLEAN_BASKET_SUCCESS = 'CLEAN_BASKET_SUCCESS';